- name: installing matchbox profiles
  template: 
    owner: "{{ matchbox.server.user }}"
    group: "{{ matchbox.server.group }}"
    src: "profiles.json.j2"
    dest: "{{ matchbox.server.profiles_dir }}/{{ item.id }}.json"
  with_items: "{{ matchbox.profiles }}"


